### PR TITLE
Added installation instructions

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Taken from https://doublecmd.sourceforge.io/forum/viewtopic.php?f=5&t=378&sid=ff25a870b749b78f8ba5977fe8115cc6&start=12#p23650

### CODE REVIEW

**Comment by Skif-off** [comment]
I think `README.md` in the root dir of project must be for all project, not for only one plugin. Also this instruction "How to compile DiskDir and install it" has not any specificity: "compile" is a standard step-by-step compiling with Lazarus for any projects and "install" is a standard step-by-step installing for any plugins.
And I hope that plugin(s) installation will be describe in Double Commander help files [here](http://doublecmd.github.io/doc/en/help.html#5_1_8_plaginy), but later :)

It looks like easy (because has not very hard dependensies, conditions and etc) and I am not sure that it's necessary in this case, but if some users have questions about DiskDir than community can and must help them :)

What are you thinking about: delete `README.md`, create `install.txt` (like in DC :)) in `/wcx/diskdir` with content something like
```
Compiling and installation DiskDir plugin

1) What you need?

Free Pascal Compiler (FPC) and Lazarus: install packages "fpc", "fpc-src" and
"lazarus" from the repository of your distribution or you can get packages
from Lazarus IDE page https://www.lazarus-ide.org/index.php?page=downloads
(DEB and RPM packages are available).
Current version of Double Commander requires at least FPC 3.0.4 and
Lazarus 1.8.2, you can use this versions for DiskDir plugin too.

2) Compiling

a) Using the Lazarus IDE to build:

- Download https://github.com/doublecmd/plugins/archive/master.zip and unpack;
- launch Lazarus IDE;
- go to "Project" > "Open Project";
- open file "plugins-master/wcx/diskdir/src/diskdir.lpi";
- go to "Run" > "Compile".

Compiled file "diskdir.wcx" will be save in "plugins-master/wcx/diskdir"

b) Building from command line:

  git clone https://github.com/doublecmd/plugins.git
  cd plugins/wcx/diskdir
  lazbuild src/diskdir.lpi

Compiled file "diskdir.wcx" will be save in current dir.

3) Installation

- Move "diskdir.wcx" in convenient dir;
- launch Double Commander;
- go to "Configuration" > "Options" > "Plugins" > "Packer plugins";
- now "Add" and choose your "diskdir.wcx";
- add extension "lst".
```
?

**Comment by ThomasLandauer** [comment]
To be honest, I don't know what the scope of this project is ;-) I was just looking for DiskDir, and I thought it would be a good idea to bring the installation instructions "closer" to the actual code. It's certainly fine with me, if you do it in another way! :-)

**Comment by Skif-off** [comment]
Sorry, I forgot :(

> To be honest, I don't know what the scope of this project is

I mean that this repository has several plugins and the building/installing instruction for DiskDir only should be in his folder, i.e. in `[repository]/wcx/diskdir/` instead `[repository]/`.

> It's certainly fine with me, if you do it in another way! :-)

I just showed an example how can make all it more beautiful :) I don't like my sketch but I don't mind if you fix this instruction as you like.

**Comment by ThomasLandauer** [comment]
Sure :-) See https://github.com/doublecmd/plugins/pull/13

**Pull request merged**
