### PR TITLE
ADD: mediainfo: Duration as a number in seconds. CHG: Rename some fields.

### PR DESCRIPTION
**Pull request by Skif-off**

### CODE REVIEW

**Comment by alexx2000** [comment]
Line endings is changed in some files. Is it intended change?

**Comment by Skif-off** [comment]
WinMerge writes that files contain different types of line ending. Also, for example: AkelPad writes "LF" (and search with regular expressions does not find `\r`), Geany writes "CRLF".
I fixed it.

Other changes in these files are not visible now and this is not very convenient, maybe make a separate PR?

**Comment by Skif-off** [comment]
Can I fix [this mistake](https://doublecmd.h1n.ru/viewtopic.php?p=34732#p34732) in this PR?

**Comment by alexx2000** [comment]
Yes.

**Comment by Skif-off** [comment]
I rewrote this PR, changes look more clear, but I don't know how to be with the type of line ending.

**Comment by Skif-off** [comment]
I added a separate commit (_FIX: mediainfo: Type of line ending (mixed LF/CRLF to LF)_, without `git rebase` and `squash`), in this case, we will get two separate commits after the merging, right?

**Comment by alexx2000** [comment]
I don't know.

> All commits from this branch will be added to the base branch via a merge commit.

**Comment by Skif-off** [comment]
It seems that this can be done, but let's go by a simple way: returned back, I will add new PR later.

**Pull request merged**
