### PR TITLE
Create installation.md

### PR DESCRIPTION
**Pull request by ThomasLandauer**

### CODE REVIEW

**Comment by Skif-off** [comment]
> 1. Copy the entire `mediainfo` directory to `/usr/lib/doublecmd/plugins/wdx/`

Why? Why not `~/,config/doublecmd/plugins`, without root privileges?

> 3. Locate the filename of your Lua library (should be similar to `liblua5.2.so.0`) inside `/usr`. If you don't have it, install it: https://www.lua.org/

If this library inside system directory (`/usr/lib` or `/usr/lib/x86_64-linux-gnu/`), then just add name.
Also GUI: Go to "Configuration" in the main menu > Options... > Plugins > _Lua library file to use_
DC supports Lua 5.1 - 5.3 and LuaJIT.

> 5. Restart Double Commander?

Need to close DC before editing the `doublecmd.xml` file. Or use ["Edit" and "Apply"](http://doublecmd.github.io/doc/en/configuration.html#ConfigDC).

**Comment by ThomasLandauer** [comment]
> Why? Why not ~/,config/doublecmd/plugins, without root privileges?

Taken from https://github.com/doublecmd/plugins/blame/master/wcx/diskdir/installation.md#L36
(which I wrote myself, lol...)
Now added your path too. Do you think it should be the first choice?

> If this library inside system directory (/usr/lib or /usr/lib/x86_64-linux-gnu/), then just add name.

Yeah, the shipped (default) value shows that filename is enough, so I didn't mention it explicitly.

> Also GUI: Go to "Configuration" in the main menu > Options... > Plugins > Lua library file to use

I don't have this in GUI (DC v0.9.8 beta). Do you know in which version it was added?

**Comment by Skif-off** [comment]
> Now added your path too. Do you think it should be the first choice?

I think yes: simple, easy, all read-write rights. `/usr` for package managers (except "/usr/local", probably).
Maybe without rigid induction, somethin like: "use a suitable place, for example, `~/,config/doublecmd/plugins`" ? I don't know, just to do it more easier than to write detailed instructions for beginners :)

> I don't have this in GUI (DC v0.9.8 beta). Do you know in which version it was added?

I think in 1.0.0.
v0.9.8 is too old (Ubuntu 20.04 or based on it?), why not the [current version](http://doublecmd.github.io/doc/en/faq.html#repo)? Also you can find portable (`doublecmd-x.x.x.gtk2.*.tar.xz` or `doublecmd-x.x.x.qt.*.tar.xz`) [here](https://github.com/doublecmd/doublecmd/releases) or [here](https://sourceforge.net/p/doublecmd/wiki/Download/), AppImage [here](https://sourceforge.net/p/doublecmd/wiki/Download/).

**Comment by ThomasLandauer** [comment]
Changed it - thanks! :-)

**Pull request merged**
